### ISSUE TITLE
Implement joystick support

### ISSUE THREAD

**Issue by roblabla** [reswitched/sdl-libtransistor#1]
It'd be nice to have joystick support, so we can use SDL's nice abstractions for it. I'll write up some implementation notes if someone wants to pick this one up.

This is a Good First Issue (I don't have the rights to add tags on issues here 😞 )

**Comment by awernick** [comment]
I'm interested in helping out! I haven't been keeping up with all the developments that have been happening with the Switch lately, but summer is coming so I'll have extra time to catch up and contribute!
How can I help?

**Comment by roblabla** [comment]
So for joystick support, you'll want to make a switch folder in [here](https://github.com/reswitched/sdl-libtransistor/tree/master/src/joystick), which is where you'll put your implementation. Copying dummy can be a good starting point. It's then mostly a matter of filling up the method with implementations. Look at [the header](https://github.com/reswitched/sdl-libtransistor/blob/b174d3cfb8fe5e9a6f9eb5ef08a7fcf54ff42bd0/src/joystick/SDL_sysjoystick.h) to know what each function must do.

Some specifics:
- Call `hid`'s [hid_init](https://github.com/reswitched/libtransistor/blob/development/include/libtransistor/hid.h#L160-L168) in JoystickInit.
- `get_shared_memory_handle` is basically instantaneous, you shouldn't need to cache it or whatever.
- `SDL_SYS_JoystickDetect` is used to detect new joysticks plugged in. It's called every tick. MIght want to just not implement it at first, from experience it's a bit of a pain to get right.

If you have some specific questions, feel free to reply or ping me on reswitched's discord :)
